'use strict';
const assert=require('node:assert/strict');
const {decodeEntities,location,proseSegments}=require('../../scripts/lib/prose');
assert.deepEqual(decodeEntities('a&#108;b'),{text:'alb',offsets:[0,1,7]});
assert.deepEqual(location('一\r\n二',3),{line:2,column:1});
const parts=proseSegments('<p>a&#108;b</p>','html');
assert.equal(parts[0].text,'alb'); assert.equal(parts[0].offset,3);
assert.equal(parts[0].offset+parts[0].offsets[1],4);
const {issue,makeReport,compareBaseline,gate}=require('../../scripts/lib/quality-report');
const old=issue({file:'a.md',rule:'placeholder',severity:'error',message:'未替换',context:'sample',line:1});
const moved=issue({file:'a.md',rule:'placeholder',severity:'error',message:'未替换',context:'sample',line:20});
assert.equal(old.id,moved.id);
const report=items=>makeReport('example',['a.md'],{engine:1},items);
const delta=compareBaseline(report([moved,moved]),report([old]));
assert.equal(delta.added.length,1); assert.equal(delta.unchanged,1);
assert.equal(gate(report([old])),1);
const warning=issue({file:'a.md',rule:'review',severity:'warning',message:'复查'});
assert.equal(gate(report([warning])),0); assert.equal(gate(report([warning]),{strict:true}),2);
console.log('prose and quality-report API examples passed.');
